### PR TITLE
feat: adding QTL effect size to genetics

### PR DESCRIPTION
**Pull request by DSuveges**
Adding new column to genetics evidence based on colocalization with QTL.
Addressing task: [#2840](https://github.com/opentargets/issues/issues/2840)

- [x] coloc read and processed.
- [x] beta mapped to SO
- [x] SO joined with l2g
- [x] pipeline run
- [x] validation

### CODE REVIEW

**Comment by DSuveges** [comment]
The schema of the generated dataset:
```
-RECORD 0----------------------------------------------------------------------------------
 beta                                  | -0.7499                                           
 betaConfidenceIntervalLower           | -0.9710371886169568                               
 betaConfidenceIntervalUpper           | -0.5287628113830433                               
 datasourceId                          | ot_genetics_portal                                
 datatypeId                            | genetic_association                               
 diseaseFromSource                     | Blood protein levels [EA, Neutrophil collagenase] 
 diseaseFromSourceMappedId             | EFO_0008248                                       
 literature                            | [28240269]                                        
 oddsRatio                             | null                                              
 oddsRatioConfidenceIntervalLower      | null                                              
 oddsRatioConfidenceIntervalUpper      | null                                              
 pValueExponent                        | -11                                               
 pValueMantissa                        | 3.0                                               
 projectId                             | GCST                                              
 publicationFirstAuthor                | Suhre K                                           
 publicationYear                       | 2017                                              
 resourceScore                         | 0.46746453642845154                               
 studyId                               | GCST004365_231                                    
 studySampleSize                       | 997                                               
 targetFromSourceId                    | ENSG00000107554                                   
 variantFunctionalConsequenceFromQtlId | null                                              
 variantFunctionalConsequenceId        | SO_0001628                                        
 variantId                             | 10_100028551_G_T                                  
 variantRsId                           | rs7896471 
```

Distribution of the SO terms:
```
+-------------------------------------+------+
|variantFunctionalConsequenceFromQtlId| count|
+-------------------------------------+------+
|                                 null|572004|
|                           SO_0002316|115182|
|                           SO_0002314| 10496|
|                           SO_0002315|114067|
+-------------------------------------+------+
```

**Comment by DSuveges** [comment]
The validation mostly successful. There are two evidence that fails validation:
```json
{
  "datasourceId": "ot_genetics_portal",
  "datatypeId": "genetic_association",
  "targetFromSourceId": "ENSG00000166377",
  "diseaseFromSourceMappedId": "UBERON_0006314",
  "publicationFirstAuthor": "FINNGEN_R6",
  "projectId": "FINNGEN",
  "publicationYear": 2022,
  "diseaseFromSource": "Abnormal findings in nipple discharge synovial fluid wound secretions",
  "studyId": "FINNGEN_R6_R18_ABNORMAL_FINDI_NIPPLE_DISCH_SYNOVIAL_FLUID_WOUND_SECRE",
  "studySampleSize": 248524,
  "pValueMantissa": 4.02,
  "pValueExponent": -8,
  "oddsRatio": 2.712145448248214,
  "oddsRatioConfidenceIntervalLower": 1.8993876789613,
  "oddsRatioConfidenceIntervalUpper": 3.872686452549837,
  "resourceScore": 0.6528323888778687,
  "variantRsId": "rs62099349",
  "variantId": "18_79030393_G_A",
  "variantFunctionalConsequenceId": "SO_0001628",
  "variantFunctionalConsequenceFromQtlId": "SO_0002316"
}
```
The reason for the failure is that `UBERON` is a not supported prefix in the disease id field.

**Review by ireneisdoomed — APPROVED** [review]
Everything makes sense. By defining an altered gene product term, we are establishing a difference between those loci that are somehow implicated in the expression of the gene - although we don't know how - and those for which we don't have information.

**Comment by ireneisdoomed** [comment]
@DSuveges I also agree with not changing the schema to include UBERONs.

**Pull request merged**
